when:
  - event: push
    branch: main
  - event: pull_request

steps:
  - name: prep
    image: golang:1.24
    pull: true
    commands:
      - go mod download
  - name: test
    image: golang:1.24
    depends_on:
      - prep
    commands:
      - go test -v ./...
